on:
  release:
    types:
      - created

name: Publish NPM Package

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org/
    - run: |
        npm install
        npm run build --if-present
        npm test
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
